version: "2"
services:
  zookeeper:
    image: confluent/zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"
      ZOOKEEPER_autopurge.purgeInterval: "0"

  kafka:
    image: wurstmeister/kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock